[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "0BSD"
repository = "https://github.com/SludgePhD/Larpa"
documentation = "https://docs.rs/larpa"
version = "0.1.0"

[workspace.dependencies]
larpa-derive = { path = "crates/larpa-derive", version = "=0.1.0" }

cov-mark = "2.1.0"
expect-test = "1.5.1"

# For size profiling.
[profile.release]
debug = "line-tables-only"
panic = "abort"
strip = "debuginfo"
lto = true
