[package]
name = "larpa-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
rust-version.workspace = true
description = "Derive macros for the `larpa` crate. Do not use. Use `larpa` directly instead."

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "1.0.66"
syn = "2.0.106"
quote = "1.0.32"

[dev-dependencies]
syn = { version = "2.0.106", features = ["extra-traits"] }
expect-test.workspace = true
